---
- name: AWX Deploy VM OS Host
  hosts: esxgroup
  connection: local
  gather_facts: no
  tasks:

  - name: Create a VM folder on given datacenter
    community.vmware.vcenter_folder:
      hostname: '{{ vcsa_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter_name: dc1
      folder_name: sample_vm_folder
      folder_type: vm
      state: present
      validate_certs: no
    register: vm_folder_creation_result
    delegate_to: localhost
