---
- name: AWX Deploy VM OS Host
  hosts: localhost
  connection: local
  gather_facts: yes

  collections: 
  - name: community.vmware
  
  tasks:
    - name: Create a VM folder on given datacenter
      community.vmware.vcenter_folder:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: datacenter_name
        folder_name: sample_vm_folder
        folder_type: vm
        state: present
      register: vm_folder_creation_result
      delegate_to: localhost
